[[dependency]]
org = "ballerinax"
name = "covid19"
version = "0.2.0"

[[dependency]]
org = "wso2"
name = "choreo.sendemail"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"